/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./public/**/*.php",
    "./public/**/*.html",
    "./public/**/*.js",
    "./lib/**/*.php",
    "./lib/**/*.html",
    "./lib/**/*.js",
    "./admin/**/*.php",
    "./admin/**/*.html",
    "./admin/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        }
      }
    },
  },
  plugins: [],
  safelist: [
    'bg-primary-600',
    'text-primary-600',
    'hover:bg-primary-700',
    'bg-red-50',
    'border-red-200',
    'text-red-400',
    'text-red-800',
    'bg-green-50',
    'border-green-200',
    'text-green-400',
    'text-green-800',
    'bg-red-200',
    'bg-red-300',
    'text-red-700',
    'text-red-900',
    'hover:bg-red-200',
    'hover:text-red-900',
    'hidden',
    'block',
    'flex',
    'grid',
    'grid-cols-12',
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-5',
    'col-span-6',
    'relative',
    'absolute',
    'fixed',
    'shadow',
    'shadow-lg',
    'rounded-md',
    'rounded-lg',
    'rounded-full',
    'rounded-t-md',
    'rounded-b-md',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-xs',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'min-h-screen',
    'h-screen',
    'min-h-[60px]',
    'w-full',
    'w-5',
    'w-6',
    'h-5',
    'h-6',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'mx-auto',
    'py-8',
    'py-2',
    'py-3',
    'px-1',
    'px-2',
    'px-3',
    'px-4',
    'sm:px-6',
    'lg:px-8',
    'space-y-6',
    'space-y-1',
    'space-x-1',
    'space-x-4',
    'gap-2',
    'mt-0.5',
    'min-w-[24px]',
    'border',
    'border-t',
    'border-b',
    'border-x',
    'border-l',
    'border-r',
    'border-gray-200',
    'border-gray-300',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-900',
    'hover:bg-gray-50',
    'hover:bg-gray-300',
    'hover:bg-red-50',
    'hover:text-red-600',
    'truncate',
    'focus:ring-primary-500',
    'focus:border-primary-500',
    'focus:outline-none',
    'hover:bg-primary-700',
    'hover:text-primary-700',
    'hover:shadow-md',
    'hover:scale-105',
    'transition',
    'transition-colors',
    'duration-200',
    'transform',
    'items-center',
    'justify-center',
    'justify-between',
    'justify-end',
    'flex-shrink-0',
    'flex-1',
    'flex-grow',
    'overflow-hidden',
    'overflow-y-auto',
    'overflow-x-auto',
    'text-center',
    'text-right',
    'text-left',
    'uppercase',
    'italic',
    'font-mono',
    'whitespace-nowrap',
    'list-disc',
    'appearance-none',
    'ring-1',
    'ring-2',
    'ring-4',
    'ring-inset',
    'ring-offset-2',
    'z-10',
    // 인쇄 관련 클래스들
    'print:hidden',
    'print:shadow-none',
    'print:border-none',
    'print:block',
    'print:text-black',
    'print:bg-white',
    // 반응형 테이블 관련 클래스들
    'sm:table-cell',
    'sm:hidden',
    'sm:block',
    'md:table-cell',
    'md:hidden',
    'table-cell',
  ],
}