/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./public/**/*.php",
    "./public/**/*.html",
    "./public/**/*.js",
    "./lib/**/*.php",
    "./lib/**/*.html",
    "./lib/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        }
      }
    },
  },
  plugins: [],
  safelist: [
    'bg-primary-600',
    'text-primary-600',
    'hover:bg-primary-700',
    'bg-red-50',
    'border-red-200',
    'text-red-400',
    'text-red-800',
    'bg-green-50',
    'border-green-200',
    'text-green-400',
    'text-green-800',
    'hidden',
    'block',
    'flex',
    'grid',
    'relative',
    'absolute',
    'fixed',
    'shadow',
    'shadow-lg',
    'rounded-md',
    'rounded-lg',
    'rounded-full',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'min-h-screen',
    'h-screen',
    'w-full',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'mx-auto',
    'py-8',
    'px-4',
    'sm:px-6',
    'lg:px-8',
    'space-y-6',
    'space-y-1',
    'space-x-4',
    'border',
    'border-t',
    'border-b',
    'border-l',
    'border-r',
    'border-gray-200',
    'border-gray-300',
    'focus:ring-primary-500',
    'focus:border-primary-500',
    'focus:outline-none',
    'hover:bg-primary-700',
    'hover:text-primary-700',
    'hover:shadow-md',
    'hover:scale-105',
    'transition',
    'transition-colors',
    'duration-200',
    'transform',
    'items-center',
    'justify-center',
    'justify-between',
    'justify-end',
    'flex-shrink-0',
    'flex-1',
    'flex-grow',
    'overflow-hidden',
    'overflow-y-auto',
    'overflow-x-auto',
    'text-center',
    'text-right',
    'text-left',
    'uppercase',
    'italic',
    'font-mono',
    'whitespace-nowrap',
    'list-disc',
    'appearance-none',
    'ring-1',
    'ring-2',
    'ring-4',
    'ring-inset',
    'ring-offset-2',
    'z-10',
  ],
}