<?php
require_once __DIR__.'/../lib/driver.php';require_once __DIR__.'/../lib/csrf.php';require_once __DIR__.'/partials/i18n.php';
mall_driver_require_login('/mall/driver/login.php');$driver=mall_driver_current();if(!$driver){header('Location:/mall/driver/login.php');exit;}$active_driver_nav='settings';$lang=driver_lang();
?>
<!doctype html><html lang="<?php echo $lang;?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>설정 - 배송기사</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><link rel="stylesheet" href="/mall/css/wanted-tokens.css"><link rel="stylesheet" href="/mall/css/mall.css"><style>
body{padding-bottom:82px;background:#f7f7f8}.head{padding:18px 20px;background:#fff;border-bottom:1px solid #eee;font-size:18px;font-weight:800}.section{margin:14px 16px;padding:18px;background:#fff;border-radius:16px;border:1px solid #e5e7eb}.section h3{margin:0 0 14px;font-size:15px}.lang-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.lang-grid a{padding:12px;text-align:center;border:1px solid #ddd;border-radius:10px;text-decoration:none;color:#555;font-weight:700}.lang-grid a.active{border-color:#1677ff;background:#eff6ff;color:#1677ff}.field{margin-bottom:14px}.field label{display:block;font-size:12px;font-weight:700;margin-bottom:5px;color:#555}.field input{width:100%;padding:11px 12px;border:1px solid #d1d5db;border-radius:9px}.work-row{display:flex;justify-content:space-between;align-items:center}.work-btn{border:0;border-radius:999px;padding:9px 15px;color:#fff;font-weight:700}.work-btn.on{background:#16a34a}.work-btn.off{background:#6b7280}.msg{display:none;padding:10px;border-radius:9px;margin-bottom:12px;font-size:13px}</style></head><body>
<div class="head"><i class="fas fa-gear"></i> 설정</div>
<section class="section"><h3>언어 설정</h3><div class="lang-grid"><a href="?lang=ko" class="<?php echo $lang==='ko'?'active':'';?>">한국어</a><a href="?lang=en" class="<?php echo $lang==='en'?'active':'';?>">English</a></div></section>
<section class="section"><h3>근무 상태</h3><div class="work-row"><span id="work-help"><?php echo $driver['is_available']?'새 배달을 받을 수 있습니다.':'새 배달 배정에서 제외됩니다.';?></span><button id="work-btn" class="work-btn <?php echo $driver['is_available']?'on':'off';?>"><?php echo $driver['is_available']?'근무 중':'근무 종료';?></button></div></section>
<section class="section"><h3>드라이버 정보</h3><div id="msg" class="msg"></div><form id="profile-form"><div class="field"><label>이름</label><input name="name" required value="<?php echo htmlspecialchars($driver['name']);?>"></div><div class="field"><label>연락처</label><input name="phone" required value="<?php echo htmlspecialchars($driver['phone']);?>"></div><div class="field"><label>차량 정보</label><input name="vehicle_info" value="<?php echo htmlspecialchars($driver['vehicle_info']??'');?>"></div><div class="field"><label>새 비밀번호 (변경할 때만 입력)</label><input name="password" type="password" minlength="8"></div><button class="btn btn-primary btn-block">저장</button></form></section>
<section class="section"><a href="/mall/driver/logout.php" style="display:block;text-align:center;color:#c8102e;font-weight:700">로그아웃</a></section>
<?php require __DIR__.'/partials/nav.php';?>
<script>var csrf=<?php echo json_encode(mall_csrf_token());?>,available=<?php echo $driver['is_available']?'true':'false';?>;function showMsg(text,ok){var m=document.getElementById('msg');m.style.display='block';m.style.background=ok?'#ecfdf5':'#fef2f2';m.style.color=ok?'#047857':'#b91c1c';m.textContent=text}
document.getElementById('profile-form').addEventListener('submit',function(e){e.preventDefault();var p=new URLSearchParams(new FormData(this));p.set('csrf_token',csrf);fetch('/mall/driver/ajax/update_profile.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p}).then(r=>r.json()).then(d=>showMsg(d.success?'저장되었습니다.':(d.error?.message||'오류가 발생했습니다.'),d.success)).catch(()=>showMsg('네트워크 오류가 발생했습니다.',false))});
document.getElementById('work-btn').addEventListener('click',function(){var b=this,next=!available,p=new URLSearchParams();p.set('is_available',next?'1':'0');p.set('csrf_token',csrf);b.disabled=true;fetch('/mall/driver/ajax/update_availability.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p}).then(r=>r.json()).then(d=>{b.disabled=false;if(!d.success)return showMsg(d.error?.message||'오류가 발생했습니다.',false);available=next;b.className='work-btn '+(next?'on':'off');b.textContent=next?'근무 중':'근무 종료';document.getElementById('work-help').textContent=next?'새 배달을 받을 수 있습니다.':'새 배달 배정에서 제외됩니다.'}).catch(()=>{b.disabled=false;showMsg('네트워크 오류가 발생했습니다.',false)})});</script></body></html>
