-- customers 테이블 현재 구조 확인
USE u622428657_homekmart;

SELECT
    COLUMN_NAME,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'u622428657_homekmart'
  AND TABLE_NAME = 'customers'
ORDER BY ORDINAL_POSITION;
